"""External evidence registry for the nowcast/forecast.

Every figure was read from the cited official/primary release (URL + as_of). Values are
transcribed, not invented; where only a growth rate or qualitative tone was disclosed, that
is what is recorded. Family: A=company, B=price, C=macro/trade, D=analyst. `targets` lists
which quarter(s) a source informs.
"""

SOURCES = [
    # --- (A) Suppliers — hard revenue ---
    dict(family="A", name="TSMC", component=["Logic", "Packaging"], targets=["Q1 2026"],
         metric="Q1 2026 revenue", value="US$35.90B (+40.6% YoY)", period="Q1 2026",
         url="https://pr.tsmc.com/english/news/3294", as_of="2026-04-10", confidence="hard",
         note="Monthly Jan-Mar; Mar NT$415.19B (+45.2% YoY); 7nm- = 74% wafer rev. Logic+CoWoS anchor."),
    dict(family="A", name="TSMC (Q2 guide)", component=["Logic", "Packaging"], targets=["Q2 2026"],
         metric="Apr 2026 actual + Q2 guidance", value="Apr NT$410.73B (+17.5% YoY); Q2 guide US$39.0-40.2B (~+10% QoQ)",
         period="Q2 2026", url="https://pr.tsmc.com/english/news/3305", as_of="2026-05-08", confidence="hard",
         note="One month of Q2 already actual; Q1 earnings-call guidance. Logic/Packaging pace anchor for Q2."),
    dict(family="A", name="SK hynix", component=["Memory"], targets=["Q1 2026", "Q2 2026"],
         metric="Q1 2026 revenue", value="KRW 52.58T (+198% YoY, +60% QoQ)", period="Q1 2026",
         url="https://news.skhynix.com/q1-2026-business-results/", as_of="2026-04-23", confidence="hard",
         note="Record; HBM ~57% share; demand exceeds 3-yr capacity. Memory anchor; Q2 LTAs locked."),
    dict(family="A", name="Micron", component=["Memory"], targets=["Q1 2026", "Q2 2026"],
         metric="FQ2 2026 revenue", value="~+196% YoY (~tripled)", period="FQ2'26 (ended ~Feb 2026, offset)",
         url="https://investors.micron.com/news-releases/news-release-details/micron-technology-inc-reports-results-second-quarter-fiscal-2026",
         as_of="2026-03-18", confidence="hard", note="Offset fiscal cal; 2026 HBM sold out. Memory corroboration."),
    dict(family="A", name="Samsung", component=["Memory"], targets=["Q1 2026", "Q2 2026"],
         metric="Q1 2026 semiconductor profit", value="memory op profit ~50x YoY", period="Q1 2026",
         url="https://news.samsung.com/global/samsung-electronics-announces-first-quarter-2026-results",
         as_of="2026-04-30", confidence="qualitative", note="Memory-led; warns 2027 shortage. Directional."),
    # --- (A) Buyers/designers — directional ---
    dict(family="A", name="NVIDIA", component=["Logic", "Auxiliary"], targets=["Q1 2026", "Q2 2026"],
         metric="Q1 FY2027 revenue", value="US$81.6B total (+85% YoY); Data Center ~90% (~$73B), ~2x YoY",
         period="FQ1'27 (~Feb-Apr 2026, offset)",
         url="https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-first-quarter-fiscal-2027",
         as_of="2026-05-20", confidence="qualitative",
         note="Buyer demand scaler; fiscal offset ~1 month. Two views of same spend as suppliers -> reconcile."),
    # --- (A) Component-specific hard anchors for Logic / Packaging / Auxiliary ---
    dict(family="A", name="TSMC HPC platform", component=["Logic"], targets=["Q1 2026", "Q2 2026"],
         metric="HPC share of revenue + QoQ", value="Q1'26 HPC = 61% of rev (record), +20% QoQ (Q4'25: 55%)",
         period="Q1 2026", url="https://en.macromicro.me/blog/tsmc-q1-earnings-call-rare-capacity-expansion-as-the-ai-megatrend-takes-shape",
         as_of="2026-04-16", confidence="hard",
         note="HPC on 3nm/5nm = AI accelerator logic dies. Direct Logic anchor (TSMC HPC > just these 4 designers)."),
    dict(family="A", name="TSMC CoWoS capacity", component=["Packaging"], targets=["Q1 2026", "Q2 2026"],
         metric="CoWoS monthly capacity 2026", value="~75-80k wpm (end-2025) -> 115-140k (end-2026); fully booked; ASP rising",
         period="2026", url="https://www.trendforce.com/news/2026/05/14/news-tsmc-sees-ai-wafer-demand-rising-11x-from-2022-2026-targets-cowos-with-24-hbm-stacks-in-2029/",
         as_of="2026-05-14", confidence="hard",
         note="CoWoS = advanced packaging (Epoch 'Packaging'). Binding constraint, fully booked -> spend ~ capacity x ASP (~+13-15%/qtr)."),
    dict(family="A", name="Broadcom (AI networking)", component=["Auxiliary"], targets=["Q1 2026", "Q2 2026"],
         metric="Q2 FY2026 AI semiconductor revenue", value="US$10.8B (+143% YoY); Q3 guide $16B; XPUs + AI networking",
         period="Q2 FY2026 (ended ~2026-05-03)",
         url="https://www.prnewswire.com/news-releases/broadcom-inc-announces-second-quarter-fiscal-year-2026-financial-results-and-quarterly-dividend-302790698.html",
         as_of="2026-06-05", confidence="hard",
         note="NVLink/AI-networking + custom ASIC = large share of Epoch 'Auxiliary'. Anchors Auxiliary growth."),
    # --- Expanded diverse sources (added 2026-06; each tagged with new_info) ---
    dict(family="A", name="TrendForce HBM (bit supply)", component=["Memory"], targets=["Q1 2026", "Q2 2026"],
         metric="HBM4 ramp + 2026 bit-supply / capex", value="HBM4 mass production 2026; bit-supply capacity-constrained; Micron capex $13.5B (+23%), SK hynix $20.5B (+17%)",
         period="2026", url="https://www.trendforce.com/presscenter/news/20251113-12780.html",
         as_of="2025-11-13", confidence="hard", new_info="volume-ceiling",
         note="Cleanroom limits cap near-term HBM bit growth -> caps the Memory VOLUME term (price unchanged)."),
    dict(family="D", name="NVIDIA Blackwell shipments", component=["Logic"], targets=["Q1 2026", "Q2 2026"],
         metric="2026 AI GPU unit shipments", value="~60k NVL72 racks / ~4.3M GPUs; Blackwell ~71% of high-end; backlog 3.6M; sold out to mid-2026",
         period="2026", url="https://finance.biggo.com/news/g-whcJ0Bq7sy_YQMfkDE",
         as_of="2025-12-29", confidence="analyst", new_info="volume",
         note="Unit-volume signal independent of TSMC revenue (which is price x wafers). Logic volume cross-check."),
    dict(family="A", name="ASE (advanced packaging)", component=["Packaging"], targets=["Q1 2026", "Q2 2026"],
         metric="2026 advanced-packaging revenue", value="~US$3.5B high-end packaging in 2026 (+10%)",
         period="2026", url="https://www.alphapilot.tech/discover/ase-technology-forecasts-3-5-billion-advanced-packaging-revenue-by-2026-amid-ai-demand",
         as_of="2026-01", confidence="hard", new_info="independent-osat",
         note="Independent OSAT (non-TSMC) packaging anchor; OSAT pace (+10%/yr) < CoWoS capacity ramp."),
    dict(family="A", name="Amkor", component=["Packaging"], targets=["Q1 2026", "Q2 2026"],
         metric="Q1 2026 net sales + 2026 capex", value="Q1'26 sales US$1,685M; 2026 capex US$2.5-3.0B (advanced packaging)",
         period="Q1 2026", url="https://www.sec.gov/Archives/edgar/data/0001047127/000104712726000017/amkr3312026erex-991.htm",
         as_of="2026-04", confidence="hard", new_info="independent-osat",
         note="Second independent OSAT anchor for Packaging."),
    dict(family="A", name="Astera Labs", component=["Auxiliary"], targets=["Q1 2026", "Q2 2026"],
         metric="Q1 2026 revenue (connectivity)", value="US$308.4M, +14% QoQ, +93% YoY (PCIe retimers, scale-up fabric)",
         period="Q1 2026", url="https://ir.asteralabs.com/news-releases/news-release-details/astera-labs-reports-first-quarter-2026-financial-results",
         as_of="2026-05-05", confidence="hard", new_info="connectivity",
         note="AI connectivity sub-segment of Auxiliary; concrete +14% QoQ growth rate."),
    dict(family="A", name="Monolithic Power", component=["Auxiliary"], targets=["Q1 2026", "Q2 2026"],
         metric="Q1 2026 Enterprise Data (AI power)", value="US$262.8M, +12.6% QoQ, +97.7% YoY; growth floor raised to ~85% YoY",
         period="Q1 2026", url="https://www.sec.gov/Archives/edgar/data/0001280452/000143774926014182/ex_929254.htm",
         as_of="2026-04", confidence="hard", new_info="power",
         note="AI power-delivery sub-segment of Auxiliary; +12.6% QoQ."),
    dict(family="D", name="Optical transceivers (InnoLight/Coherent)", component=["Auxiliary"], targets=["Q1 2026", "Q2 2026"],
         metric="AI optical module market", value="datacom 800G+ market ~$9B (2024) -> ~$16B (2026); InnoLight +123% YoY, >50% of NVIDIA optical",
         period="2026", url="https://research.fpx.world/p/part-2-beyond-power-the-networking",
         as_of="2026", confidence="analyst", new_info="optical",
         note="Optical interconnect sub-segment of Auxiliary; fast-growing, independent of switch ASICs."),
    dict(family="B", name="Murata MLCC (passives price)", component=["Auxiliary"], targets=["Q2 2026"],
         metric="AI-server MLCC price increase", value="+15-35% effective 2026-04-01; AI servers use 10-15x MLCCs",
         period="Q2 2026", url="https://www.digitimes.com/news/a20260218VL202/murata-mlcc-capacity-ai-server-demand.html",
         as_of="2026-03-17", confidence="hard-price", new_info="passives-price",
         note="Passive-component price uplift hitting Q2; supports the Q2 Auxiliary nudge."),
    # --- (B) Memory price indices ---
    dict(family="B", name="TrendForce", component=["Memory"], targets=["Q1 2026"],
         metric="Q1 2026 DRAM contract price QoQ", value="~+95% DRAM; NAND up; HBM tight (LTA)", period="Q1 2026",
         url="https://www.trendforce.com/presscenter/news/20260202-12911.html", as_of="2026-02-02",
         confidence="hard-price", note="Free PR. Memory price x volume decomposition; HBM more LTA-priced."),
    dict(family="B", name="TrendForce (2Q26)", component=["Memory"], targets=["Q2 2026"],
         metric="Q2 2026 contract price QoQ forecast", value="DRAM +58-63%; NAND +70-75%; server/HBM prioritized",
         period="Q2 2026", url="https://www.trendforce.com/presscenter/news/20260331-12995.html", as_of="2026-03-31",
         confidence="hard-price", note="Free PR. Shortage into 2027-28; HBM LTA rises less than spot DRAM."),
    # --- (C) Macro / trade ---
    dict(family="C", name="Korea MOTIE/customs", component=["all"], targets=["Q1 2026", "Q2 2026"],
         metric="Mar 2026 semiconductor exports YoY", value="~+200% (through 20th); record monthly exports",
         period="Mar 2026",
         url="https://en.sedaily.com/finance/2026/04/01/semiconductor-power-defies-war-monthly-exports-head-toward",
         as_of="2026-04-01", confidence="macro", note="Record Q1 exports, chip-led. Quarter-pace calibration."),
    dict(family="C", name="FRED IPG3344S", component=["all"], targets=["Q1 2026", "Q2 2026"],
         metric="US semiconductor industrial production index", value="<fetched live>", period="monthly",
         url="https://fred.stlouisfed.org/series/IPG3344S", as_of="fetched at runtime", confidence="macro",
         note="Downloaded as CSV by loaders; recent YoY used as pace cross-check."),
    # --- (D) Analyst estimates ---
    dict(family="D", name="Morgan Stanley (VR200 BoM)", component=["Memory", "Packaging", "Auxiliary"],
         targets=["Q2 2026"], metric="NVL72 rack bill-of-materials (GB300 -> VR200)",
         value="rack ~$4.0M -> $7.8M; Memory +435% (->26% of system); GPU +57%; PCB +233%; MLCC +182%; ABF +82%",
         period="2026 (VR200 ships Q3, ramps Q4)",
         url="https://www.tomshardware.com/tech-industry/artificial-intelligence/nvidias-memory-costs-soar-485-percent-latest-ai-systems-now-cost-usd7-8-million-to-build-memory-now-comprises-25-percent-of-the-total-cost-rubin-gpus-a-mere-usd50-000-apiece",
         as_of="2026-06", confidence="analyst",
         note="Morgan Stanley Research (user-provided exhibit + corroboration). RACK/system BoM, broader than "
              "Epoch chip-component scope; used as memory-share trajectory + upside, not Q2 base mix (Q2 = Blackwell)."),
]

NOT_OBTAINED = [
    "Taiwan MOEA export orders (corroborated by TSMC + Korea)",
    "SEMI billings / book-to-bill",
    "OSAT (ASE, Amkor) packaging revenue",
    "Exact NVIDIA DC / Samsung DS / Micron USD figures (used growth rates / shares instead)",
    "Hyperscaler 2026 capex consensus, HBM TAM analyst $ (qualitative direction only)",
]

FRED_SERIES = "IPG3344S"
FRED_CSV_URL = "https://fred.stlouisfed.org/graph/fredgraph.csv?id=IPG3344S"
